version: '3.8'

services:
  nextjs-app:
    container_name: nextjs-container
    build: .
    ports:
      - "3000:3000" # Mapea el puerto del contenedor al puerto de tu máquina/servidor
    restart: always # Reinicia automáticamente en caso de fallo
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
